### ISSUE TITLE
ssh-agent doesn't work correctly unless run from shell

### ISSUE THREAD

**Issue by evilhamsterman** [Keeper-Security/Commander#1088]
Not sure if this is just due to the fact that we use SSO. But starting a ssh-agent works fine from the keeper shell, however starting it direct from the terminal it doesn't respect the persistent login from my SSO session, and it doesn't find my sshKey record

**Comment by sk-keeper** [comment]
Thank you for reporting this issue.
`ssh-agent` is defined as command that does not require authentication.
So, Commander does not make sure a session is authenticated. 
This issue will be fixed in the next release.
Meanwhile you can create a batch file like
```
ls
ssh-agent start
```
and start Commander as
```
keeper <batch file>
```
`ls` command will force Commander to authenticate.

**Comment by evilhamsterman** [comment]
It does appear this is resolved in 16.9.21
