### ISSUE TITLE
Missing `LICENSE` file.

### ISSUE THREAD

**Issue by BOPOHA** [Keeper-Security/Commander#129]
```
$ pip --version
pip 9.0.1 from ~/.virtualenvs/py3.6.1/lib/python3.6/site-packages (python 3.6)

$ pip install keepercommander  --no-binary :all:
Collecting keepercommander
  Using cached https://files.pythonhosted.org/packages/3a/ff/957141dcbd5b6b193332ede5dde87f0d0076e04b8361ae886f51a6f2c42f/keepercommander-3.9.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hqliqwyr/keepercommander/setup.py", line 11, in <module>
        LICENSE = open("LICENSE").read()
    FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hqliqwyr/keepercommander/
You are using pip version 9.0.1, however version 19.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by sk-keeper** [comment]
https://github.com/Keeper-Security/Commander/pull/130

**Comment by sk-keeper** [comment]
This issue is duplicated with "python:3.6.1-alpine" docker image.
By Installing the following binary wheel packages, you'll be able to resume keepercommander installation.
https://pypi.org/project/lxml/#files
https://pypi.org/project/pycryptodomex/#files

In case of "python:3.6.1-alpine" docker image the wheel package needs to be renamed:
'manylinux1' to 'linux'
i.e.
'lxml-4.3.3-cp36-cp36m-manylinux1_x86_64.whl' 
to 
'lxml-4.3.3-cp36-cp36m-linux_x86_64.whl'

**Comment by yuralar** [comment]
Thanks, I don’t use binary wheel packages at all. The enterprise requires you to build everything from the source code.

**Comment by BOPOHA** [comment]
@yuralar, @sk-keeper Thanks!
