### ISSUE TITLE
connect:xxx with same xxx but in different folders

### ISSUE THREAD

**Issue by lsntomaszw** [Keeper-Security/Commander#207]
we have the same names of connection in different folders eg:

```
> connect
...
 23  nfs                        machines        /lsn/est/uat1
 24  nfs                        machines        /lsn/est/prod
 25  nfs                        machines        /lsn/est/prep
 26  nfs                        machines        /lsn/est/uat2
 27  nfs                        NFS             /iot/dev
 28  nfs                        NFS             /lsn/afc/local
```

and we'd like to connect to a particular one by providing full connection name eg:

```
connect /iot/dev/nfs
```

or  by

```
keeper connect /iot/dev/nfs
```

but for some reason, it selects just the ``nfs`` from another folder. 

it was working ok in 4.9, was not in 4.12 and it's still not working in 4.24

what is more - being in THE folder and calling 

```
connect nfs
```

is also picking ``nfs`` entry from a different folder

**Comment by sk-keeper** [comment]
Yes starting commander v4.10, 'connect' command does not require full path to the record anymore.
Unfortunately, compatibility with the previous version was broken if connection endpoint entry is not unique.
It is going to be fixed in the next Commander release. The endpoint for connect is going to have the following format:
/<Folder Path>/<Record Title>:<Endpoint Name>
path to the record or endpoint name can be dropped. 
Example
`keeper connect /iot/dev/nfs:nfs`
or
`keeper connect /iot/dev/nfs`
or 
`keeper connect nfs`

**Comment by craiglurey** [comment]
Fixed.  Updating PyPi
