### ISSUE TITLE
Keeper chrome extension vuejs issue

### ISSUE THREAD

**Issue by john-ko** [Keeper-Security/Commander#304]
Hello

first off the issue is with the chrome extension but I dont know if that repo is public or not, so I decided to make an issue here (i know its the wrong place for it)

background:
- we running vuejs server side rendering, and client side hydration on our websites
- when users navigate to our site with keeper chrome extension parts of the page would be missing
- when vuejs has a DOM - virtual DOM mismatch, it bails hydration and leaves content empty
- `https://www.hunker.com/13724276/leather-wrapped-vase-planter-tutorial` (url that has an issue)

we believe keeper is updating the dom (we think input fields) then vuejs is having a DOM mismatch and failing

any insights would be helpful

thanks

**Comment by THeflinKeeper** [comment]
Yes, keeper is updating the dom. Keeper adds lock icons for users to click on so that the extension window can popup on the page. In order to prevent these lock icons from being populated on your page, here are a couple suggestions:
1. Disable Display Locks: you can achieve this by going to the browser-action window of the extension and toggling the Display Locks toggle if you are logged into the extension
2. Disable Domain: If you are part of an enterprise, you can change an enforcement to restrict the extension from being used on a site. To do this, you would first login to your enterprise as the admin of that enterprise, click on the Admin button on the left, click on the Roles button, create a new role if you dont have one already or click on an existing role, click Enterprise Policies on the right, in the popup click Keeperfill, then include the domain in the Disable KeeperFill on Specified Websites section.

**Comment by john-ko** [comment]
thanks for info!

i'll go ahead and close this issue
