### ISSUE TITLE
How to edit custom data fields using --data

### ISSUE THREAD

**Issue by yphoenix** [Keeper-Security/Commander#906]
The documentation says to use --custom
When you try to use --custom you get the message

> Record NNNNNN is version 3 already. Please use version 3 editing options (--data, --from-file, option)

So I try and work out how to use --data for a custom field and mange to destroy the contents of the entry in the process.

a. a failed format should never destroy the contents of a record
b. what is the format for updating custom records?

Thanks

**Comment by yphoenix** [comment]
I can't use `c.secret.field=value` because the field name has spaces in it and when I try I get the following:

> Error(s) converting options to a record type: ["Invalid field value: {'secret': [{'field name with spaces': 'foo'}]}"]

**Comment by yphoenix** [comment]
I really don't want to have to start doing `custom_field_name` type of field names, because that is not user friendly to our users.

**Comment by sk-keeper** [comment]
Commander has another command for updating record fields: `record-update`
Command syntax is `record-update --record "<RECORD UID>" field1=value2 field2=value2 ...`
where field 
1. type
2. label
3. type.label
`record-update --syntax-help` 

If `secret` custom field has a unique label ( for instance "La bel") then it can be referenced as
`"La bel=<SECRET VALUE>"` or `secret."La bel"=<SECRET VALUE>`
The latter syntax is preferable because `record-update` will create a  custom field if it cannot be found on a record.

**Comment by yphoenix** [comment]
Thanks I'll try that.

**Comment by yphoenix** [comment]
Thanks that works. Hopefully the documentation will be updated to include this command as this is much simpler.
