### ISSUE TITLE
Cannot update security data for rec_uid = abracadabra

### ISSUE THREAD

**Issue by groner** [Keeper-Security/Commander#974]
This warning is somewhat concerning to see. Is my data being saved?

Looking at where it originates from, it appears to be a normal path for most records?
https://github.com/Keeper-Security/Commander/blob/48a6c9f31cd84edbdaaeb6265f6cee02d228f181/keepercommander/breachwatch.py#L156-L160

**Comment by aaunario-keeper** [comment]
No, your data is not being saved. 

That part of the code merely calculates and updates security data associated with password-containing records in your vault. These security data include metrics such as password strength, BreachWatch status (a kind of set of metadata. if you like), etc., but NEVER values that are either contained in the record itself (e.g., password, title, login URL) or that can be mapped to those values. 

The security data being saved in this case are completely anonymized and in strict adherence with our "Zero Knowledge" design philosophy here at Keeper. 

Regarding the output that you may sometimes see upon doing a BreachWatch scan of records (when command execution hits line 160 in the code that you highlight above):  it is somewhat extraneous and unnecessarily potentially confusing (as it's not always appropriate to associate security data w/ any given record); Thus, you can rest assured that it will be improved in the next release of Commander. We appreciate you bringing this issue to our attention so that we may correct it as promptly as possible.  Thank you.

**Comment by groner** [comment]
I want to clarify that my concern about data being saved is about whether an new or updated record would be retrievable later, not other forms of data collection or surveillance.
